server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-config-tarifa-duracion
          uri: lb://ms-config-tarifa-duracion
          predicates:
            - Path=/tarifas/**

        - id: ms-desc-client-frecuente
          uri: lb://ms-desc-client-frecuente
          predicates:
            - Path=/clientes/**

        - id: ms-desc-num-personas
          uri: lb://ms-desc-num-personas
          predicates:
            - Path=/descuento-grupo/**

        - id: ms-rack-semanal
          uri: lb://ms-rack-semanal
          predicates:
            - Path=/rack/**

        - id: ms-reportes
          uri: lb://ms-reportes
          predicates:
            - Path=/reportes/**

        - id: ms-reserva-comprobante
          uri: lb://ms-reserva-comprobante
          predicates:
            - Path=/reservas/**

        - id: ms-tarifa-especial
          uri: lb://ms-tarifa-especial
          predicates:
            - Path=/tarifa-especial/**