server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservadb
    username: root
    password: nueva_clave
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka