spring:
  jpa:
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true

servicios:
  reservas:
    url: http://localhost:8085
  comprobantes:
    url: http://localhost:8085
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka